name: CI
on:
  workflow_dispatch:
jobs:
  build:
    name: build
    runs-on: unbuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Enviorment Install
      run: |
        apt install texinfo bison automake -y
        apt install gcc g++ gcc-multilib g++-multilib -y
        apt install make -y
        
    - name: Enviorment Checkout
      run: |
       gcc -v
       g++ -v
    - name: configure
      run: |
        mkdir build && cd build
        ../configure --prefix=/gcc/ --disable-nls --disable-werror
    - name: build
      run: |
        make all-install -j
    - name: Upload release assets
      uses: actions/upload-artifact@v1
      with:
          name: my-artifact
          path: /gcc/

  
  
