on:
  workflow_dispatch:
jobs:
  build:
    name: build
    runs-on: unbuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Enviorment checkout
      run: |
        gcc -v
        g++ -v
